name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Install Dependencies"
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm nodejs npm aylurs-gtk-shell
          npm install -g sass

      - name: Build DireWolf
        run: |
          make ags-deployment

      - name: Verify build output exists
        run: |
          test -f dist/DireWolf
      - name: Update VERSION file
        run: |
          echo "${{ github.ref_name }}" > VERSION

      - name: Rename release binary
        run: |
          cp dist/DireWolf dist/DireWolf-${{ github.ref_name }}

      - name: Create GitHub release
        run: |
          gh release create ${{ github.ref_name }} \
            dist/DireWolf-${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --notes "Release of DireWolf version ${{ github.ref_name }}." \
            --generate-notes"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
